### ISSUE TITLE
Support syncing on iPod nano 7th generation software version 1.0.3 and newer

### ISSUE THREAD

**Issue by reupen** [reupen/ipod_manager#2]

**Comment by rKsanu2MMYvypWePtQWM** [comment]
It works fine for me on nano7 1.0.4 (manager 0.7.0)

**Comment by reupen** [comment]
> It works fine for me on nano7 1.0.4 (manager 0.7.0)

Yep, I forgot about this issue – it was fixed in 0.7.0 https://github.com/reupen/ipod_manager/releases/tag/0.7.0

> edit - instead of creating a new "issue" for a simple question, I'll ask it here - can I sync playlists from the ipod to foobar? "Manage contents" doesn't show my custom playlists.

Do you mean playlists created on the device? It may be that they aren't being loaded correctly. Create another issue and I'll have a look at it.

However, there's no way to convert iPod playlists to playlists pointing at files on your PC. You can load playlists into foobar2000 using View/iPod devices though (they will play files directly from your iPod).
