### ISSUE TITLE
Files with chapters

### ISSUE THREAD

**Issue by templarundead** [reupen/ipod_manager#4]
Any plans for files with chapters supporting?

**Comment by reupen** [comment]
Are you referring to the 'Files with chapters are not currently supported by foo_dop' error?

Unfortunately chapters are quite complicated, and it's not easily fixed (in a nice way). The iPod and iTunes use them differently to foobar2000 – they're used for e.g. podcasts and don't split a track into multiple ones in the same way foobar2000 does.

However, if the file is in an unsupported format, it will work in that the component will transcode the chapters into separate tracks.

**Comment by templarundead** [comment]
Anyway thanks you for the hard work.
